<a href="https://colab.research.google.com/github/varmagsr/AIMLProj/blob/main/NLPPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install spacy
!python -m spacy download en_core_web_md


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
2022-08-23 21:24:34.614831: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 42.8 MB 372 kB/s 
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')


In [ ]:
class Category:
  BOOKS = "BOOKS"
  CLOTHING = "CLOTHING"

train_x = ["i love the book", "this is a great book", "the fit is great", "i love the shoes"]
train_y = [Category.BOOKS, Category.BOOKS, Category.CLOTHING, Category.CLOTHING]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(binary=True, ngram_range=(1,2))
train_x_vectors = vectorizer.fit_transform(train_x)

print(train_x_vectors[0])

print(vectorizer.get_feature_names_out())
print(train_x_vectors.toarray())


  (0, 7)	1
  (0, 10)	1
  (0, 0)	1
  (0, 8)	1
  (0, 11)	1
['book' 'fit' 'fit is' 'great' 'great book' 'is' 'is great' 'love'
 'love the' 'shoes' 'the' 'the book' 'the fit' 'the shoes' 'this'
 'this is']
[[1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0]
 [1 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1]
 [0 1 1 1 0 1 1 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0]]


In [ ]:
from sklearn import svm

clf_svm = svm.SVC(kernel='linear')
clf_svm.fit(train_x_vectors, train_y)

SVC(kernel='linear')

In [ ]:
test_x = vectorizer.transform(['shoes looks good'])

clf_svm.predict(test_x)


array(['CLOTHING'], dtype='<U8')

## Word Vectors


In [ ]:
import spacy
nlp = spacy.load("en_core_web_md")

In [ ]:
print(train_x)

['i love the book', 'this is a great book', 'the fit is great', 'i love the shoes']


In [ ]:
docs = [nlp(text) for text in train_x]
#print(docs[0].vector)
train_x_word_vectors = [x.vector for x in docs]

In [ ]:
from sklearn import svm
clf_svm_wv = svm.SVC(kernel='linear')
clf_svm_wv.fit(train_x_word_vectors, train_y)

SVC(kernel='linear')

In [ ]:
test_x = ["i love the reading"]
test_docs = [nlp(text) for text in test_x]
test_x_word_vectors = [x.vector for x in test_docs]

clf_svm_wv.predict(test_x_word_vectors)

array(['BOOKS'], dtype='<U8')

# **RegExp**

In [ ]:
import re


#regexp = re.compile(r"ab[^\s]*cd")
regexp = re.compile(r"\bread\b|\bstory\b|book")

phrases = ["I liked that story", "the car teared up the hill", "this hat is nice"]

matches = []
for phrase in phrases:
  #if re.match(regexp, phrase):
  if re.match(regexp, phrase):
    matches.append(phrase)

print(matches)

[]


# **Stemming/Lemmatization**

Techniques to normalize test

**Stemmer technique** will shorten the words like from "Reading" to Read and Books to Book, however there are few know issues like stories turns into stori.



In [ ]:
import nltk
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [ ]:
from nltk.tokenize import word_tokenize
from nltk import PorterStemmer

stemmer = PorterStemmer()

phrase = "coming from gardening."
words = word_tokenize(phrase)

stemmed_words = []
for word in words:
  stemmed_words.append(stemmer.stem(word))

" ".join(stemmed_words)




'come from garden .'

In [ ]:
from nltk.stem import WordNetLemmatizer

# Init the Wordnet Lemmatizer
lemmatizer = WordNetLemmatizer()

phrase = "reading the stories."
words = word_tokenize(phrase)

lemmatized_words = []
for word in words:
  lemmatized_words.append(lemmatizer.lemmatize(word, pos='v'))

" ".join(lemmatized_words)


'read the stories .'

# Stopwords Removal

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

stop_words = stopwords.words('english')

phrase = "hear is an example sentance demonstrating the removal of stopwords"

words = word_tokenize(phrase)

stripped_phrase = []
for word in words:
  if word not in stop_words:
    stripped_phrase.append(word)

" ".join(stripped_phrase)


'hear example sentance demonstrating removal stopwords'

# Various other Techniques (Spell correction, Sentiment, & PartOfSpeach(pos) tagging

In [ ]:
!python -m textblob.download_corpora

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package conll2000 to /root/nltk_data...
[nltk_data]   Unzipping corpora/conll2000.zip.
[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Unzipping corpora/movie_reviews.zip.
Finished.


In [ ]:
from textblob import TextBlob

phrase = "the book was horrible"

tb_phrase = TextBlob(phrase)

tb_phrase.correct()

tb_phrase.tags

tb_phrase.sentiment

Sentiment(polarity=-1.0, subjectivity=1.0)


# Transformer Architecture

# Setup

In [ ]:


!pip install spacy-transformers
!python -m spacy download en_core_web_trf
!python -m spacy download en_core_web_lg



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 53 kB 868 kB/s 
     |████████████████████████████████| 1.1 MB 8.9 MB/s 
     |████████████████████████████████| 4.7 MB 38.2 MB/s 
     |████████████████████████████████| 6.6 MB 42.3 MB/s 
     |████████████████████████████████| 120 kB 29.6 MB/s 
2022-08-23 21:25:41.138141: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 460.3 MB 34 kB/s 
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')
2022-08-23 21:27:46.157168: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Looking in indexes: https://pyp

# Using Spacy to utilize BERT Model

In [33]:
import numpy as np
import spacy
import torch

nlp = spacy.load("en_core_web_trf")
doc = nlp("Apple shares rose on the news. Apple pie is delicious.")

ValueError: ignored

In [31]:
class Category:
  BOOKS = "BOOKS"
  BANK = "BANK"

train_x = ["good characters and plot progression", "check out the book", "good story. would recommend", "novel recommendation", "need to make a deposit to the bank", "balance inquiry savings", "save money"]
train_y = [Category.BOOKS, Category.BOOKS, Category.BOOKS, Category.BOOKS, Category.BANK, Category.BANK, Category.BANK]


In [43]:
from sklearn import svm

docs = [nlp(text) for text in train_x]
#train_x_vectors = np.array([doc.vector for doc in docs]).reshape(-1,1)
train_x_vectors = [doc.vector for doc in docs]
clf_svm = svm.SVC(kernel='linear')


clf_svm.fit(train_x_vectors, train_y)

test_x = ["Send me the check to withdraw"]
docs = [nlp(text) for text in test_x]
test_x_vectors = [doc.vector for doc in docs]

clf_svm.predict(test_x_vectors)


array(['BANK'], dtype='<U5')

***All credits & Referance:-  https://github.com/KeithGalli/pycon2020.***
